"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Stethoscope } from "lucide-react";
import { calculateAccuracy } from "@/lib/scoring";
import { findClinic, saveSubmission } from "@/lib/storage";
import { Clinic, DiagnosisCategory, StudentSubmission } from "@/lib/types";

const categories:DiagnosisCategory[]=["Isi","Huraian","Contoh","Tatabahasa","Kosa kata","Organisasi","Fakta","Penanda wacana"];
export default function StudentPage(){
 const [code,setCode]=useState("DKAI26"),[name,setName]=useState(""); const [clinic,setClinic]=useState<Clinic|null>(null); const [step,setStep]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [category,setCategory]=useState<DiagnosisCategory>("Isi"),[reason,setReason]=useState("");
 const [diagnoses,setDiagnoses]=useState<StudentSubmission["diagnoses"]>([]); const [scores,setScores]=useState({isi:5,bahasa:5,organisasi:5}); const [improved,setImproved]=useState(""),[reflection,setReflection]=useState(""); const [accuracy,setAccuracy]=useState(0);
 const join=()=>{const c=findClinic(code);if(c&&name.trim()){setClinic(c);setStep(1)}else alert("Sila masukkan nama dan kod klinik yang sah.")};
 const addDiagnosis=()=>{if(selected===null||!reason.trim())return;setDiagnoses(d=>[...d.filter(x=>x.sentenceIndex!==selected),{sentenceIndex:selected,category,reason}]);setReason("");setSelected(null)};
 const submit=()=>{if(!clinic)return;const value=calculateAccuracy(clinic,diagnoses);setAccuracy(value);saveSubmission({id:crypto.randomUUID(),clinicCode:clinic.code,studentName:name,diagnoses,scores,improvedParagraph:improved,reflection,accuracy:value,createdAt:new Date().toISOString()});setStep(5)};
 return <main className="shell"><header className="topbar"><Link className="brand" href="/"><div className="brandMark"><Stethoscope size={22}/></div><div className="brandText">Doktor Karangan AI<small>Bilik Rawatan Murid</small></div></Link></header><div className="page">{!clinic?<><div className="pageHead"><div><Link href="/" className="sub"><ArrowLeft size={15}/> Laman utama</Link><h2>Daftar Pesakit</h2><p className="sub">Masukkan kod yang diberikan oleh guru untuk memulakan pemeriksaan.</p></div></div><div className="card" style={{maxWidth:560,margin:'0 auto'}}><div className="field"><label>Nama doktor murid</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nama anda"/></div><div className="field"><label>Kod klinik</label><input className="input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Contoh: DKAI26"/></div><button className="btn btnPrimary" style={{width:'100%'}} onClick={join}>Masuk Klinik</button><p className="sub" style={{fontSize:13}}>Kod demo: <b>DKAI26</b></p></div></>:<><div className="steps">{["Pemeriksaan","Diagnosis","Rubrik","Rawatan","Refleksi","Laporan"].map((s,i)=><span className={`step ${step===i?'active':''}`} key={s}>{i+1}. {s}</span>)}</div>{step===1&&<div className="grid"><section className="card"><h3>Fail Pesakit: {clinic.title}</h3><p className="sub">{clinic.level} • Karangan {clinic.essayType} • {clinic.topic}</p><div className="essay">{clinic.sentences.map((s,i)=><span key={i} className={`sentence ${selected===i?'selected':''}`} onClick={()=>setSelected(i)}>{s} </span>)}</div></section><section className="card"><h3>Catatan diagnosis</h3>{selected===null?<div className="notice">Klik satu ayat yang mempunyai masalah.</div>:<><div className="notice success">Ayat {selected+1} dipilih.</div><div className="field"><label>Kategori</label><select className="select" value={category} onChange={e=>setCategory(e.target.value as DiagnosisCategory)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Mengapa ayat ini bermasalah?</label><textarea className="textarea" value={reason} onChange={e=>setReason(e.target.value)}/></div><button className="btn btnGreen" onClick={addDiagnosis}>Simpan diagnosis</button></>}<div className="diagnosisList" style={{marginTop:16}}>{diagnoses.map((d,i)=><div className="diagnosisItem" key={i}><b>Ayat {d.sentenceIndex+1} • {d.category}</b><span>{d.reason}</span></div>)}</div><button className="btn btnPrimary" style={{width:'100%',marginTop:16}} onClick={()=>setStep(2)} disabled={!diagnoses.length}>Teruskan ke Rubrik</button></section></div>}
 {step===2&&<section className="card" style={{maxWidth:720,margin:'0 auto'}}><h3>Pemeriksaan Tahap Kesihatan</h3>{([['isi','Isi'],['bahasa','Bahasa'],['organisasi','Organisasi']] as const).map(([k,l])=><div className="rubricRow" key={k}><b>{l}</b><input type="range" min="0" max="10" value={scores[k]} onChange={e=>setScores({...scores,[k]:Number(e.target.value)})}/><strong>{scores[k]}</strong></div>)}<div className="notice">Jumlah markah anda: <b>{scores.isi+scores.bahasa+scores.organisasi}/30</b></div><button className="btn btnPrimary" onClick={()=>setStep(3)} style={{marginTop:16}}>Rancang Rawatan</button></section>}
 {step===3&&<section className="card" style={{maxWidth:820,margin:'0 auto'}}><h3>Rawat Satu Perenggan</h3><p className="sub">Tulis semula bahagian paling lemah. Tambah huraian, contoh atau bahasa yang lebih tepat.</p><textarea className="textarea" style={{minHeight:220}} value={improved} onChange={e=>setImproved(e.target.value)} placeholder="Versi yang telah diperbaik..."/><button className="btn btnPrimary" onClick={()=>setStep(4)} disabled={improved.trim().length<20}>Teruskan</button></section>}
 {step===4&&<section className="card" style={{maxWidth:820,margin:'0 auto'}}><h3>Refleksi Literasi AI</h3><p className="sub">Adakah karangan yang kelihatan lancar semestinya tepat dan berkualiti? Terangkan apa yang masih memerlukan pertimbangan manusia.</p><textarea className="textarea" style={{minHeight:180}} value={reflection} onChange={e=>setReflection(e.target.value)}/><button className="btn btnGreen" onClick={submit} disabled={reflection.trim().length<15}>Hantar Laporan</button></section>}
 {step===5&&<div className="grid"><section className="card"><h3>Ketepatan Diagnosis</h3><div className="scoreCircle" style={{'--score':accuracy} as React.CSSProperties}><strong>{accuracy}%</strong></div><p className="sub">Skor mengambil kira diagnosis tepat dan diagnosis tambahan yang tidak sepadan dengan skema.</p><div className="notice success"><CheckCircle2 size={17}/> Laporan anda telah dihantar.</div></section><section className="card"><h3>Pendapat Kedua AI</h3><p>{clinic.aiFeedback}</p><h3>Skema tersembunyi</h3><div className="diagnosisList">{clinic.issues.map((i,n)=><div className="diagnosisItem" key={n}><b>Ayat {i.sentenceIndex+1} • {i.category}</b><span>{i.explanation}</span></div>)}</div><div className="notice" style={{marginTop:14}}>Markah anda: <b>{scores.isi+scores.bahasa+scores.organisasi}/30</b> • Skema guru: <b>{clinic.teacherScores.isi+clinic.teacherScores.bahasa+clinic.teacherScores.organisasi}/30</b></div></section></div>}</>}</div></main>
}
