"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BarChart3, Download, Plus, Stethoscope } from "lucide-react";
import { defaultClinic } from "@/lib/demo-data";
import { getSubmissions, saveClinic } from "@/lib/storage";
import { Clinic, DiagnosisCategory, EssayType, Level } from "@/lib/types";

const categories: DiagnosisCategory[] = ["Isi","Huraian","Contoh","Tatabahasa","Kosa kata","Organisasi","Fakta","Penanda wacana"];
const uid=()=>crypto.randomUUID();
const makeCode=()=>`DK${Math.random().toString(36).slice(2,6).toUpperCase()}`;

export default function TeacherPage(){
 const [tab,setTab]=useState<"create"|"dashboard">("create");
 const [title,setTitle]=useState("Klinik Karangan Baharu"); const [className,setClassName]=useState("2G3");
 const [level,setLevel]=useState<Level>("G3"); const [essayType,setEssayType]=useState<EssayType>("ekspositori");
 const [topic,setTopic]=useState("Kesan penggunaan media sosial terhadap remaja"); const [focus,setFocus]=useState<DiagnosisCategory[]>(["Huraian","Contoh","Kosa kata","Fakta","Organisasi"]);
 const [clinic,setClinic]=useState<Clinic|null>(null); const [loading,setLoading]=useState(false);
 const submissions=useMemo(()=>typeof window!=="undefined"?getSubmissions():[],[tab,clinic]);
 const generate=async()=>{setLoading(true);try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,level,essayType,focus})});const data=await res.json();const next:Clinic={...data,id:uid(),code:makeCode(),title,className,level,essayType,topic,createdAt:new Date().toISOString()};saveClinic(next);setClinic(next);}catch{const next={...defaultClinic,id:uid(),code:makeCode(),title,className,level,essayType,topic,createdAt:new Date().toISOString()};saveClinic(next);setClinic(next);}finally{setLoading(false)}};
 const exportCsv=()=>{const rows=[["Nama","Kod","Ketepatan","Isi","Bahasa","Organisasi","Refleksi"],...submissions.map(s=>[s.studentName,s.clinicCode,s.accuracy,s.scores.isi,s.scores.bahasa,s.scores.organisasi,s.reflection])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='doktor-karangan-respons.csv';a.click();};
 const avg=submissions.length?Math.round(submissions.reduce((a,s)=>a+s.accuracy,0)/submissions.length):0;
 return <main className="shell"><header className="topbar"><Link className="brand" href="/"><div className="brandMark"><Stethoscope size={22}/></div><div className="brandText">Doktor Karangan AI<small>Portal Guru</small></div></Link><div className="navActions"><button className={`btn ${tab==='create'?'btnPrimary':'btnGhost'}`} onClick={()=>setTab('create')}><Plus size={17}/> Bina</button><button className={`btn ${tab==='dashboard'?'btnPrimary':'btnGhost'}`} onClick={()=>setTab('dashboard')}><BarChart3 size={17}/> Dashboard</button></div></header>
 <div className="page">{tab==='create'?<><div className="pageHead"><div><Link href="/" className="sub"><ArrowLeft size={15}/> Laman utama</Link><h2>Bina Klinik Karangan</h2><p className="sub">Tetapkan kes, pilih simptom sasaran dan semak karangan sebelum kelas bermula.</p></div></div><div className="grid"><section className="card"><h3>1. Maklumat klinik</h3><div className="field"><label>Nama aktiviti</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><div className="field"><label>Kelas</label><input className="input" value={className} onChange={e=>setClassName(e.target.value)}/></div><div className="field"><label>Tahap</label><select className="select" value={level} onChange={e=>setLevel(e.target.value as Level)}><option>G1</option><option>G2</option><option>G3</option></select></div></div><div className="field"><label>Jenis karangan</label><div className="segmented"><button className={`segment ${essayType==='ekspositori'?'active':''}`} onClick={()=>setEssayType('ekspositori')}>Ekspositori</button><button className={`segment ${essayType==='naratif'?'active':''}`} onClick={()=>setEssayType('naratif')}>Naratif</button></div></div><div className="field"><label>Topik</label><textarea className="textarea" value={topic} onChange={e=>setTopic(e.target.value)}/></div><div className="field"><label>Fokus diagnosis</label><div className="chips">{categories.map(c=><button key={c} className={`chip ${focus.includes(c)?'active':''}`} onClick={()=>setFocus(f=>f.includes(c)?f.filter(x=>x!==c):[...f,c])}>{c}</button>)}</div></div><button className="btn btnPrimary" style={{width:'100%'}} onClick={generate} disabled={loading}>{loading?'Menjana kes klinik...':'Jana Karangan Pesakit'}</button></section>
 <section className="card"><h3>2. Pratonton guru</h3>{clinic?<><div className="codeBox"><small>KOD KLINIK</small><strong>{clinic.code}</strong></div><p className="essay">{clinic.essay}</p><div className="notice success"><b>{clinic.issues.length} simptom tersembunyi.</b> Skema guru dan pendapat kedua AI hanya dipaparkan selepas murid menghantar rawatan.</div></>:<div className="empty">Karangan pesakit akan muncul di sini selepas dijana.</div>}</section></div></>:<><div className="pageHead"><div><h2>Dashboard Klinik</h2><p className="sub">Gambaran formatif respons yang disimpan pada peranti ini.</p></div><button className="btn btnGhost" onClick={exportCsv}><Download size={17}/> CSV</button></div><div className="dashboardStats"><div className="miniStat"><small>Respons</small><strong>{submissions.length}</strong></div><div className="miniStat"><small>Purata ketepatan</small><strong>{avg}%</strong></div><div className="miniStat"><small>Selesai</small><strong>{submissions.length}</strong></div><div className="miniStat"><small>Perlu sokongan</small><strong>{submissions.filter(s=>s.accuracy<50).length}</strong></div></div><section className="card"><h3>Prestasi murid</h3>{submissions.length?submissions.map(s=><div className="diagnosisItem" key={s.id} style={{display:'flex',justifyContent:'space-between',gap:12}}><div><b>{s.studentName}</b><small>{s.clinicCode} • {s.scores.isi+s.scores.bahasa+s.scores.organisasi}/30</small></div><strong>{s.accuracy}% tepat</strong></div>):<div className="empty">Belum ada respons. Gunakan kod DKAI26 untuk mencuba aliran murid demo.</div>}</section></>}</div></main>
}
